WITH Needed AS(
    SELECT TaxID
    FROM ORDER O, ORDER_INCLUDE OI, TOY_BUILDING_SET T
    WHERE O.OID = OI.OID AND T.SID = OI.SID AND Date >= 01/01/2022 
            AND Date <= 31/12/2022
    GROUP BY TaxID, O.OID 
    HAVING COUNT(DISTINCT Category) >3;
)
SELECT City, Date, COUNT(DISTINCT TaxID)
FROM CUSTOMER C, ORDER O 
WHERE O.TaxID = C.TaxID AND O.TaxID NOT IN Needed AND 
        Date >= 01/01/2022 AND Date <= 31/12/2022 
GROUP BY City, Date;