WITH Need AS(
    SELECT SID 
    FROM SONG S, RADIO_PROGRAMMING P 
    WHERE S.Language = 'Italian' AND S.SID = P.SID 
        AND StartTime <= '14:00' 
)
SELECT Name, Network
FROM WEBRADIO W, RADIO_PROGRAMMING RP, SONG S1
WHERE RP.WID = W.WID AND S1.SID = RP.SID 
    S1.Language = 'Italian' AND SID NOT IN (SELECT SID FROM Needed)
GROUP BY WID, Name, Network
HAVING COUNT(DISTINCT SID) > 100;